name: env_var_github_actions

on: push

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variable
      run: |
        echo "::set-env name=LD_LIBRARY_PATH::${{ env.HOME }}/.local/lib:$LD_LIBRARY_PATH"
        
    - name: Print environment variable
      run: |
        echo "############################"
        echo $LD_LIBRARY_PATH
        echo ${{ env.LD_LIBRARY_PATH }}
        echo "############################"
