name: env_var_github_actions

on: push

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        echo "::set-env name=FOO::$HOME/.local/lib:$LD_LIBRARY_PATH"
        echo "::set-env name=LD_LIBRARY_PATH::$HOME/.local/lib:$LD_LIBRARY_PATH"
        
    - name: Print environment variables
      run: |
        echo FOO=$FOO
        echo FOO=${{ env.FOO }}
        echo "############################"
        echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
        echo LD_LIBRARY_PATH=${{ env.LD_LIBRARY_PATH }}
        echo "############################"
