name: env_var_github_actions

on: push

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      LD_LIBRARY_PATH: foo/bar
      FOO: BAR

    steps:
    - uses: actions/checkout@v2
        
    - name: Print environment variables
      run: |
        echo "------------------"
        echo FOO=$FOO
        echo "------------------"
        echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
        echo "------------------"
